### ISSUE TITLE
Problems with -use

### ISSUE THREAD

**Issue by fotisk07** [lcswillems/python-MNIST-classifier#2]
$ python main.py --out test --mode use
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 10)                7850      
_________________________________________________________________
activation (Activation)      (None, 10)                0         
=================================================================
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "main.py", line 74, in <module>
    ui.build(model)
  File "/home/fotis/Desktop/Programming/python-MNIST-classifier-master/ui.py", line 138, in build
    reset()
  File "/home/fotis/Desktop/Programming/python-MNIST-classifier-master/ui.py", line 101, in reset
    classify()
  File "/home/fotis/Desktop/Programming/python-MNIST-classifier-master/ui.py", line 74, in classify
    imgs = utils.preprocess(img)
  File "/home/fotis/Desktop/Programming/python-MNIST-classifier-master/utils/data.py", line 98, in preprocess
    img2 = shrink_center(img1)
  File "/home/fotis/Desktop/Programming/python-MNIST-classifier-master/utils/data.py", line 73, in shrink_center
    img = skimage.transform.resize(img, (rows, cols), anti_aliasing=True, mode='constant')
AttributeError: module 'skimage' has no attribute 'transform'

**Comment by fotisk07** [comment]
This only happens with version 0.16.1.

**Comment by lcswillems** [comment]
Okay, thank you for reporting this! I will try to have a look. Again, if you mind doing a PR, it would be great!

**Comment by lcswillems** [comment]
I have just fixed this issue.
